" Enable modern features
set nocompatible 
syntax on
filetype plugin indent on

""" Loading plugins
source ~/.vim/plugins.vim

"" Encoding
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
set ttyfast

" Tabs
set tabstop=2
set shiftwidth=2
set expandtab
set linebreak
set showbreak=+++
set textwidth=80

" change split direction
set splitright
set splitbelow


"" Fix backspace indent
set backspace=indent,eol,start

" Finding files
set path+=**
set wildmenu

""" temporary files
set nobackup
set nowritebackup
set noconfirm
set noswapfile

""" Navigation improvemements
set number
set autoindent
set nofoldenable
set mouse=a mousemodel=popup_setpos

"" Map leader to space
let mapleader=' '

"" Enable hidden buffers
set hidden

"" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Editor theme
set termguicolors
let ayucolor="mirage"
colorscheme ayu

set t_Co=256


" session management
let g:session_directory = "~/./session"
let g:session_autoload = "yes"
let g:session_autosave = "yes"
let g:session_command_aliases = 1

" IndentLine
let g:indentLine_enabled = 1
let g:indentLine_faster = 1
let g:indentLine_fileTypeExclude = ["nerdtree", "markdown", "json"]


""" Shortcuts
cnoreabbrev W! w!
cnoreabbrev Q! q!
cnoreabbrev Qall! qall!
cnoreabbrev Wq wq
cnoreabbrev Wa wa
cnoreabbrev wQ wq
cnoreabbrev WQ wq
cnoreabbrev W w
cnoreabbrev Q q
cnoreabbrev Qall qall

nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l
nmap <leader><space> :noh<CR>

" bufer navigation
nmap <silent> + :bnext<CR>
nmap <silent> _ :bprev<CR>
nmap <silent> <leader>c :bd<CR>

nmap YY "+y<CR>
nmap <leader>p "+gP<CR>
nmap XX "+x<CR>

nmap <leader>v :vsp $MYVIMRC<cr>
nmap <leader>V :source $MYVIMRC<cr>

" terminal emulation
nnoremap <silent> <leader>sh :terminal<CR>

" FZF
" let g:fzf_layout = { 'window': { 'width': 1, 'height': 0.4, 'yoffset': 1, 'border': 'horizontal' } }

" NERDTree configuration
let g:NERDTreeChDirMode=2
let NERDTreeIgnore = [
\ '\.pyc$',
\ '__pycache__',
\ 'node_modules',
\ 'venv',
\ '\.serverless',
\ '\.idea',
\ '\.git'
\ ]
let g:NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$', '\.bak$', '\~$']
let g:NERDTreeShowBookmarks=0
let g:nerdtree_tabs_focus_on_files=1
let g:NERDTreeMapOpenInTabSilent = '<RightMouse>'
let g:NERDTreeWinSize = 50


set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite
" nnoremap <silent> <F3> :NERDTreeToggle<CR>
" nnoremap <silent> <F2> :NERDTreeFind<CR>

nnoremap <silent> <leader>n :NERDTreeToggle<CR>
nnoremap <silent> <leader>r :NERDTreeFind<CR>

" CoC

let g:coc_global_extensions = [
\ 'coc-cfn-lint',
\ 'coc-clangd',
\ 'coc-css',
\ 'coc-cssmodules',
\ 'coc-docker',
\ 'coc-emmet',
\ 'coc-eslint',
\ 'coc-go',
\ 'coc-html',
\ 'coc-json',
\ 'coc-pairs',
\ 'coc-python',
\ 'coc-snippets',
\ 'coc-solargraph',
\ 'coc-stylelintplus',
\ 'coc-tsserver',
\ 'coc-yaml',
\ ]

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
set signcolumn=number

" the autocomplete popup size
" set pumwidth=60
" set pumheight=20

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
" inoremap <silent><expr> <TAB>
"       \ pumvisible() ? "\<C-n>" :
"       \ <SID>check_back_space() ? "\<TAB>" :
"       \ coc#refresh()
" inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
inoremap <silent><expr> <TAB>
\ pumvisible() ? coc#_select_confirm() :
\ coc#expandableOrJumpable() ? 
\ "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
\ <SID>check_back_space() ? "\<TAB>" :
\ coc#refresh()

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
" position. Coc only does snippet and additional edit on confirm.
" <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.
if exists('*complete_info')
  inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
else
  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
endif

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Formatting selected code.
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap keys for applying codeAction to the current buffer.
nmap <leader>ac  <Plug>(coc-codeaction)
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Add (Neo)Vim's native statusline support.
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline.
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}


""" Commands
" remove trailing whitespaces
command! FixWhitespace :%s/\s\+$//e
