"""""""""""""""
"   PLUGINS   "
"""""""""""""""

let vimplugpath=expand('~/./autoload/plug.vim')
let curl=expand('curl')

if !filereadable(vimplugpath)
  if !executable(curl)
    echoerr "vim-plug is not installed. Reason: curl does not exist."
    execute "q!"
  endif
  echo "Installing Vim-Plug..."
  echo ""
  let plugurl = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  silent exec "!"curl " -fLo " . shellescape(vimplugpath) . " --create-dirs " . plugurl
  let g:not_finish_vimplug = "yes"

  autocmd VimEnter * PlugInstall
endif



call plug#begin('~/.vim/plugged')

" universal modert vim settings
Plug 'tpope/vim-sensible'

" Colorscheme
Plug 'ayu-theme/ayu-vim'
" Plug 'morhetz/gruvbox'

" FZF
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
Plug 'junegunn/fzf.vim'

" Vim Session
Plug 'xolox/vim-misc'
Plug 'xolox/vim-session'

" supporting wrapping
Plug 'tpope/vim-surround'

" Supporting comments
Plug 'tpope/vim-commentary'

" support case changes
Plug 'tpope/vim-abolish'

" Indent line
Plug 'Yggdroot/indentLine'

" Trailing whitespace highlighting & automatic fixing
Plug 'ntpeters/vim-better-whitespace'

" File explorer
Plug 'preservim/nerdtree'

" replace occurrences in many buffers being aware of the context
Plug 'pelodelfuego/vim-swoop'

" airline the status bar
Plug 'vim-airline/vim-airline'

" coc
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'honza/vim-snippets'

" syntax highlighting support
Plug 'sheerun/vim-polyglot'

" git
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'

" ruby
Plug 'tpope/vim-rails'
Plug 'tpope/vim-rake'
Plug 'tpope/vim-projectionist'
Plug 'thoughtbot/vim-rspec'
Plug 'ecomba/vim-ruby-refactoring', {'tag': 'main'}
Plug 'vim-test/vim-test'

" go
Plug 'fatih/vim-go', {'do': ':GoInstallBinaries'}

" html
Plug 'hail2u/vim-css3-syntax'
Plug 'gko/vim-coloresque'
Plug 'tpope/vim-haml'
Plug 'mattn/emmet-vim'

" javascript
Plug 'jelera/vim-javascript-syntax'
Plug 'kchmck/vim-coffee-script'
Plug 'peitalin/vim-jsx-typescript'

" python
Plug 'davidhalter/jedi-vim'
Plug 'raimon49/requirements.txt.vim', {'for': 'requirements'}

" typescript
Plug 'leafgarland/typescript-vim'
Plug 'HerringtonDarkholme/yats.vim'

" markdown
Plug 'plasticboy/vim-markdown'

" ripgrep
Plug 'jremmen/vim-ripgrep'

call plug#end()



""""""""""""""""
"   SETTINGS   "
""""""""""""""""

" Enable modern features
set nocompatible
syntax on
filetype plugin indent on

"" Encoding
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
set ttyfast

" Tabs
set tabstop=2
set shiftwidth=2
set expandtab
set linebreak
set showbreak=+++
set textwidth=80

" change split direction
set splitright
set splitbelow


"" Fix backspace indent
set backspace=indent,eol,start

" Finding files
set path+=**
set wildmenu

""" temporary files
set nobackup
set nowritebackup
set noconfirm
set noswapfile

""" Navigation improvemements
set number
set autoindent
set nofoldenable
set mouse=a mousemodel=popup_setpos

"" Map leader to space
let mapleader=' '

"" Enable hidden buffers
set hidden

"" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Editor theme
set t_Co=256
set termguicolors
" let ayucolor="light"  " for light version of theme
let ayucolor="mirage" " for mirage version of theme
" let ayucolor="dark"   " for dark version of theme
colorscheme ayu
" colorscheme gruvbox

""" vim-airline
let g:airline#extensions#tabline#enabled = 0
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline#extensions#tabline#show_splits = 0 " disable buffers toggle on the tabline
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = ''
let g:airline#extensions#tabline#right_sep = ''
let g:airline#extensions#tabline#right_alt_sep = ''
let g:airline#extensions#tabline#show_close_button = 0
let g:airline#extensions#tabline#show_tab_type = 0
let g:airline#extensions#tabline#show_tab_nr = 0
let g:airline#extensions#tabline#fnamecollapse = 1


""" session management
let g:session_directory = "~/./session"
let g:session_autoload = "yes"
let g:session_autosave = "yes"
let g:session_command_aliases = 1

""" IndentLine
let g:indentLine_enabled = 1
let g:indentLine_faster = 1
let g:indentLine_fileTypeExclude = ["nerdtree", "markdown", "json"]


""" vim-better-whitespace
let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1
let g:strip_whitespace_confirm=0
let g:strip_whitelines_at_eof=1


""" Shortcuts
cnoreabbrev W! w!
cnoreabbrev Q! q!
cnoreabbrev Qall! qall!
cnoreabbrev Wq wq
cnoreabbrev Wa wa
cnoreabbrev wQ wq
cnoreabbrev WQ wq
cnoreabbrev W w
cnoreabbrev Q q
cnoreabbrev Qall qall

nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l
nmap <leader><space> :noh<CR>

" bufer navigation
nmap <silent> + :bnext<CR>
nmap <silent> _ :bprev<CR>
nmap <silent> <leader>q :bdelete<CR>

" quickfix navigation
nmap <silent> <leader>co :copen<CR>
nmap <silent> <leader>cc :cclose<CR>

nmap YY "+y<CR>
nmap <leader>p "+gP<CR>
nmap XX "+x<CR>

nmap <leader>v :vsp $MYVIMRC<cr>
nmap <leader>V :source $MYVIMRC<cr>

" terminal emulation
nnoremap <silent> <leader>sh :terminal<CR>

" FZF
" let g:fzf_layout = { 'window': { 'width': 1, 'height': 0.4, 'yoffset': 1, 'border': 'horizontal' } }
nnoremap <silent> <leader>b :Buffers<CR>
nnoremap <silent> <leader>t :Files<CR>

" vim-fugitive
nmap <leader>gj :diffget \\3<cr>
nmap <leader>gf :diffget \\2<cr>
nmap <leader>gs :G<cr>

" NERDTree configuration
let g:NERDTreeChDirMode=2
let NERDTreeIgnore = [
\ '\.pyc$',
\ '__pycache__',
\ 'node_modules',
\ 'venv',
\ '\.serverless',
\ '\.idea',
\ '\.git'
\ ]
let g:NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$', '\.bak$', '\~$']
let g:NERDTreeShowBookmarks=0
let g:nerdtree_tabs_focus_on_files=1
let g:NERDTreeMapOpenInTabSilent = '<RightMouse>'
let g:NERDTreeWinSize = 50


set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite
" nnoremap <silent> <F3> :NERDTreeToggle<CR>
" nnoremap <silent> <F2> :NERDTreeFind<CR>

nnoremap <silent> <leader>n :NERDTreeToggle<CR>
nnoremap <silent> <leader>r :NERDTreeFind<CR>

" vim-rails / vim-projectionist
nnoremap <silent> <leader>A  :A<CR>
nnoremap <silent> <leader>AV :AV<CR>
nnoremap <silent> <leader>AS :AS<CR>
nnoremap <silent> <leader>AT :AT<CR>

nnoremap <silent> <leader>R  :R<CR>
nnoremap <silent> <leader>RV :RV<CR>
nnoremap <silent> <leader>RS :RS<CR>
nnoremap <silent> <leader>RT :RT<CR>

" CoC

let g:coc_global_extensions = [
\ 'coc-clangd',
\ 'coc-css',
\ 'coc-cssmodules',
\ 'coc-docker',
\ 'coc-emmet',
\ 'coc-eslint',
\ 'coc-go',
\ 'coc-html',
\ 'coc-json',
\ 'coc-pairs',
\ 'coc-python',
\ 'coc-snippets',
\ 'coc-solargraph',
\ 'coc-stylelintplus',
\ 'coc-tsserver',
\ 'coc-yaml',
\ ]

""" vim-gitgutter
set signcolumn=yes
let g:gitgutter_sign_allow_clobber = 1
let g:gitgutter_set_sign_backgrounds = 1

" the autocomplete popup size
" set pumwidth=60
" set pumheight=20

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
" inoremap <silent><expr> <TAB>
"       \ pumvisible() ? "\<C-n>" :
"       \ <SID>check_back_space() ? "\<TAB>" :
"       \ coc#refresh()
" inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
inoremap <silent><expr> <TAB>
\ pumvisible() ? coc#_select_confirm() :
\ coc#expandableOrJumpable() ?
\ "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
\ <SID>check_back_space() ? "\<TAB>" :
\ coc#refresh()

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
" position. Coc only does snippet and additional edit on confirm.
" <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.
if exists('*complete_info')
  inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
else
  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
endif

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Formatting selected code.
xmap <leader>f  <Plug>(coc-format)
nmap <leader>f  <Plug>(coc-format)
xmap <leader>F  <Plug>(coc-format-selected)
nmap <leader>F  <Plug>(coc-format-selected)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap keys for applying codeAction to the current buffer.
nmap <leader>ac  <Plug>(coc-codeaction)
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Add (Neo)Vim's native statusline support.
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline.
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}


""" Commands
" remove trailing whitespaces
command! FixWhitespace :%s/\s\+$//e
